# Site
title:              外刊兔-免费提供最新的《经济学人》《纽约客》《科学》高清PDF下载
bio:                '真正会学英语的人都在外刊兔读外刊~'
description:        "外刊兔是一个免费提供最新经济学人、纽约客、科学期刊的高清PDF下载的网站。浏览高质量外文期刊，无需订阅费用，随时满足您的知识渴望。"
keywords:           "经济学人 PDF MOBI EPUB 下载, The Economist,The NewYorkwe,Science, 经济学人, 经济学人音频, 经济学人下载"
reading_time:       true
words_per_minute:   200
logo:               'https://cdn.jsdelivr.net/gh/liuhaiyan1992/lhycdn/logo4.svg'
background:         'https://cdn.jsdelivr.net/gh/liuhaiyan1992/lhycdn/light_1.webp'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://waikantu.com

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            username
facebook:           username
github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
